/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SuccessStory {
    id: bigint;
    title: string;
    content: string;
    date: Time;
    authorName: string;
    village: string;
    category: BusinessCategory;
}
export type Time = bigint;
export interface TrainingResource {
    id: bigint;
    url: string;
    title: string;
    description: string;
    resourceType: ResourceType;
    category: ResourceCategory;
}
export interface Entrepreneur {
    id: Principal;
    age: bigint;
    bio: string;
    contactInfo: string;
    businessCategory: BusinessCategory;
    fullName: string;
    district: string;
    state: string;
    panchayat: string;
    village: string;
    gender: Gender;
    skills: Array<string>;
}
export interface CommunityPost {
    id: bigint;
    author: Principal;
    panchayat: string;
    message: string;
    village: string;
    timestamp: Time;
    category: BusinessCategory;
}
export enum BusinessCategory {
    other = "other",
    food = "food",
    environment = "environment",
    sustainability = "sustainability",
    agriculture = "agriculture"
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum ResourceCategory {
    food = "food",
    environment = "environment",
    general = "general",
    sustainability = "sustainability",
    agriculture = "agriculture"
}
export enum ResourceType {
    video = "video",
    tool = "tool",
    guide = "guide",
    course = "course"
}
export interface backendInterface {
    addCommunityPost(post: CommunityPost): Promise<void>;
    addSuccessStory(story: SuccessStory): Promise<void>;
    addTrainingResource(resource: TrainingResource): Promise<void>;
    getEntrepreneur(user: Principal): Promise<Entrepreneur>;
    listCommunityPosts(): Promise<Array<CommunityPost>>;
    listEntrepreneurs(): Promise<Array<Entrepreneur>>;
    listSuccessStories(): Promise<Array<SuccessStory>>;
    listTrainingResources(): Promise<Array<TrainingResource>>;
    registerEntrepreneur(entrepreneur: Entrepreneur): Promise<void>;
}
import type { BusinessCategory as _BusinessCategory, CommunityPost as _CommunityPost, Entrepreneur as _Entrepreneur, Gender as _Gender, ResourceCategory as _ResourceCategory, ResourceType as _ResourceType, SuccessStory as _SuccessStory, Time as _Time, TrainingResource as _TrainingResource } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCommunityPost(arg0: CommunityPost): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCommunityPost(to_candid_CommunityPost_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCommunityPost(to_candid_CommunityPost_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addSuccessStory(arg0: SuccessStory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSuccessStory(to_candid_SuccessStory_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSuccessStory(to_candid_SuccessStory_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTrainingResource(arg0: TrainingResource): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrainingResource(to_candid_TrainingResource_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrainingResource(to_candid_TrainingResource_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getEntrepreneur(arg0: Principal): Promise<Entrepreneur> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntrepreneur(arg0);
                return from_candid_Entrepreneur_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntrepreneur(arg0);
            return from_candid_Entrepreneur_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCommunityPosts(): Promise<Array<CommunityPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCommunityPosts();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCommunityPosts();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async listEntrepreneurs(): Promise<Array<Entrepreneur>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEntrepreneurs();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEntrepreneurs();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSuccessStories(): Promise<Array<SuccessStory>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSuccessStories();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSuccessStories();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTrainingResources(): Promise<Array<TrainingResource>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTrainingResources();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTrainingResources();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerEntrepreneur(arg0: Entrepreneur): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerEntrepreneur(to_candid_Entrepreneur_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerEntrepreneur(to_candid_Entrepreneur_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_BusinessCategory_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BusinessCategory): BusinessCategory {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_CommunityPost_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommunityPost): CommunityPost {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Entrepreneur_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Entrepreneur): Entrepreneur {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_ResourceCategory_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResourceCategory): ResourceCategory {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_ResourceType_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResourceType): ResourceType {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_SuccessStory_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SuccessStory): SuccessStory {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_TrainingResource_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrainingResource): TrainingResource {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    age: bigint;
    bio: string;
    contactInfo: string;
    businessCategory: _BusinessCategory;
    fullName: string;
    district: string;
    state: string;
    panchayat: string;
    village: string;
    gender: _Gender;
    skills: Array<string>;
}): {
    id: Principal;
    age: bigint;
    bio: string;
    contactInfo: string;
    businessCategory: BusinessCategory;
    fullName: string;
    district: string;
    state: string;
    panchayat: string;
    village: string;
    gender: Gender;
    skills: Array<string>;
} {
    return {
        id: value.id,
        age: value.age,
        bio: value.bio,
        contactInfo: value.contactInfo,
        businessCategory: from_candid_BusinessCategory_n15(_uploadFile, _downloadFile, value.businessCategory),
        fullName: value.fullName,
        district: value.district,
        state: value.state,
        panchayat: value.panchayat,
        village: value.village,
        gender: from_candid_Gender_n17(_uploadFile, _downloadFile, value.gender),
        skills: value.skills
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    author: Principal;
    panchayat: string;
    message: string;
    village: string;
    timestamp: _Time;
    category: _BusinessCategory;
}): {
    id: bigint;
    author: Principal;
    panchayat: string;
    message: string;
    village: string;
    timestamp: Time;
    category: BusinessCategory;
} {
    return {
        id: value.id,
        author: value.author,
        panchayat: value.panchayat,
        message: value.message,
        village: value.village,
        timestamp: value.timestamp,
        category: from_candid_BusinessCategory_n15(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: string;
    date: _Time;
    authorName: string;
    village: string;
    category: _BusinessCategory;
}): {
    id: bigint;
    title: string;
    content: string;
    date: Time;
    authorName: string;
    village: string;
    category: BusinessCategory;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        date: value.date,
        authorName: value.authorName,
        village: value.village,
        category: from_candid_BusinessCategory_n15(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    url: string;
    title: string;
    description: string;
    resourceType: _ResourceType;
    category: _ResourceCategory;
}): {
    id: bigint;
    url: string;
    title: string;
    description: string;
    resourceType: ResourceType;
    category: ResourceCategory;
} {
    return {
        id: value.id,
        url: value.url,
        title: value.title,
        description: value.description,
        resourceType: from_candid_ResourceType_n29(_uploadFile, _downloadFile, value.resourceType),
        category: from_candid_ResourceCategory_n31(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    food: null;
} | {
    environment: null;
} | {
    sustainability: null;
} | {
    agriculture: null;
}): BusinessCategory {
    return "other" in value ? BusinessCategory.other : "food" in value ? BusinessCategory.food : "environment" in value ? BusinessCategory.environment : "sustainability" in value ? BusinessCategory.sustainability : "agriculture" in value ? BusinessCategory.agriculture : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    tool: null;
} | {
    guide: null;
} | {
    course: null;
}): ResourceType {
    return "video" in value ? ResourceType.video : "tool" in value ? ResourceType.tool : "guide" in value ? ResourceType.guide : "course" in value ? ResourceType.course : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    food: null;
} | {
    environment: null;
} | {
    general: null;
} | {
    sustainability: null;
} | {
    agriculture: null;
}): ResourceCategory {
    return "food" in value ? ResourceCategory.food : "environment" in value ? ResourceCategory.environment : "general" in value ? ResourceCategory.general : "sustainability" in value ? ResourceCategory.sustainability : "agriculture" in value ? ResourceCategory.agriculture : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CommunityPost>): Array<CommunityPost> {
    return value.map((x)=>from_candid_CommunityPost_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Entrepreneur>): Array<Entrepreneur> {
    return value.map((x)=>from_candid_Entrepreneur_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SuccessStory>): Array<SuccessStory> {
    return value.map((x)=>from_candid_SuccessStory_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TrainingResource>): Array<TrainingResource> {
    return value.map((x)=>from_candid_TrainingResource_n27(_uploadFile, _downloadFile, x));
}
function to_candid_BusinessCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessCategory): _BusinessCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_CommunityPost_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CommunityPost): _CommunityPost {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Entrepreneur_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Entrepreneur): _Entrepreneur {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_ResourceCategory_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceCategory): _ResourceCategory {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_ResourceType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceType): _ResourceType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_SuccessStory_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SuccessStory): _SuccessStory {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_TrainingResource_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrainingResource): _TrainingResource {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    author: Principal;
    panchayat: string;
    message: string;
    village: string;
    timestamp: Time;
    category: BusinessCategory;
}): {
    id: bigint;
    author: Principal;
    panchayat: string;
    message: string;
    village: string;
    timestamp: _Time;
    category: _BusinessCategory;
} {
    return {
        id: value.id,
        author: value.author,
        panchayat: value.panchayat,
        message: value.message,
        village: value.village,
        timestamp: value.timestamp,
        category: to_candid_BusinessCategory_n3(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    age: bigint;
    bio: string;
    contactInfo: string;
    businessCategory: BusinessCategory;
    fullName: string;
    district: string;
    state: string;
    panchayat: string;
    village: string;
    gender: Gender;
    skills: Array<string>;
}): {
    id: Principal;
    age: bigint;
    bio: string;
    contactInfo: string;
    businessCategory: _BusinessCategory;
    fullName: string;
    district: string;
    state: string;
    panchayat: string;
    village: string;
    gender: _Gender;
    skills: Array<string>;
} {
    return {
        id: value.id,
        age: value.age,
        bio: value.bio,
        contactInfo: value.contactInfo,
        businessCategory: to_candid_BusinessCategory_n3(_uploadFile, _downloadFile, value.businessCategory),
        fullName: value.fullName,
        district: value.district,
        state: value.state,
        panchayat: value.panchayat,
        village: value.village,
        gender: to_candid_Gender_n35(_uploadFile, _downloadFile, value.gender),
        skills: value.skills
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: string;
    date: Time;
    authorName: string;
    village: string;
    category: BusinessCategory;
}): {
    id: bigint;
    title: string;
    content: string;
    date: _Time;
    authorName: string;
    village: string;
    category: _BusinessCategory;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        date: value.date,
        authorName: value.authorName,
        village: value.village,
        category: to_candid_BusinessCategory_n3(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    url: string;
    title: string;
    description: string;
    resourceType: ResourceType;
    category: ResourceCategory;
}): {
    id: bigint;
    url: string;
    title: string;
    description: string;
    resourceType: _ResourceType;
    category: _ResourceCategory;
} {
    return {
        id: value.id,
        url: value.url,
        title: value.title,
        description: value.description,
        resourceType: to_candid_ResourceType_n9(_uploadFile, _downloadFile, value.resourceType),
        category: to_candid_ResourceCategory_n11(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceType): {
    video: null;
} | {
    tool: null;
} | {
    guide: null;
} | {
    course: null;
} {
    return value == ResourceType.video ? {
        video: null
    } : value == ResourceType.tool ? {
        tool: null
    } : value == ResourceType.guide ? {
        guide: null
    } : value == ResourceType.course ? {
        course: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceCategory): {
    food: null;
} | {
    environment: null;
} | {
    general: null;
} | {
    sustainability: null;
} | {
    agriculture: null;
} {
    return value == ResourceCategory.food ? {
        food: null
    } : value == ResourceCategory.environment ? {
        environment: null
    } : value == ResourceCategory.general ? {
        general: null
    } : value == ResourceCategory.sustainability ? {
        sustainability: null
    } : value == ResourceCategory.agriculture ? {
        agriculture: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessCategory): {
    other: null;
} | {
    food: null;
} | {
    environment: null;
} | {
    sustainability: null;
} | {
    agriculture: null;
} {
    return value == BusinessCategory.other ? {
        other: null
    } : value == BusinessCategory.food ? {
        food: null
    } : value == BusinessCategory.environment ? {
        environment: null
    } : value == BusinessCategory.sustainability ? {
        sustainability: null
    } : value == BusinessCategory.agriculture ? {
        agriculture: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
