/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BusinessCategory = { 'other' : null } |
  { 'food' : null } |
  { 'environment' : null } |
  { 'sustainability' : null } |
  { 'agriculture' : null };
export interface CommunityPost {
  'id' : bigint,
  'author' : Principal,
  'panchayat' : string,
  'message' : string,
  'village' : string,
  'timestamp' : Time,
  'category' : BusinessCategory,
}
export interface Entrepreneur {
  'id' : Principal,
  'age' : bigint,
  'bio' : string,
  'contactInfo' : string,
  'businessCategory' : BusinessCategory,
  'fullName' : string,
  'district' : string,
  'state' : string,
  'panchayat' : string,
  'village' : string,
  'gender' : Gender,
  'skills' : Array<string>,
}
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export type ResourceCategory = { 'food' : null } |
  { 'environment' : null } |
  { 'general' : null } |
  { 'sustainability' : null } |
  { 'agriculture' : null };
export type ResourceType = { 'video' : null } |
  { 'tool' : null } |
  { 'guide' : null } |
  { 'course' : null };
export interface SuccessStory {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'date' : Time,
  'authorName' : string,
  'village' : string,
  'category' : BusinessCategory,
}
export type Time = bigint;
export interface TrainingResource {
  'id' : bigint,
  'url' : string,
  'title' : string,
  'description' : string,
  'resourceType' : ResourceType,
  'category' : ResourceCategory,
}
export interface _SERVICE {
  'addCommunityPost' : ActorMethod<[CommunityPost], undefined>,
  'addSuccessStory' : ActorMethod<[SuccessStory], undefined>,
  'addTrainingResource' : ActorMethod<[TrainingResource], undefined>,
  'getEntrepreneur' : ActorMethod<[Principal], Entrepreneur>,
  'listCommunityPosts' : ActorMethod<[], Array<CommunityPost>>,
  'listEntrepreneurs' : ActorMethod<[], Array<Entrepreneur>>,
  'listSuccessStories' : ActorMethod<[], Array<SuccessStory>>,
  'listTrainingResources' : ActorMethod<[], Array<TrainingResource>>,
  'registerEntrepreneur' : ActorMethod<[Entrepreneur], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];