/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const BusinessCategory = IDL.Variant({
  'other' : IDL.Null,
  'food' : IDL.Null,
  'environment' : IDL.Null,
  'sustainability' : IDL.Null,
  'agriculture' : IDL.Null,
});
export const CommunityPost = IDL.Record({
  'id' : IDL.Nat,
  'author' : IDL.Principal,
  'panchayat' : IDL.Text,
  'message' : IDL.Text,
  'village' : IDL.Text,
  'timestamp' : Time,
  'category' : BusinessCategory,
});
export const SuccessStory = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Time,
  'authorName' : IDL.Text,
  'village' : IDL.Text,
  'category' : BusinessCategory,
});
export const ResourceType = IDL.Variant({
  'video' : IDL.Null,
  'tool' : IDL.Null,
  'guide' : IDL.Null,
  'course' : IDL.Null,
});
export const ResourceCategory = IDL.Variant({
  'food' : IDL.Null,
  'environment' : IDL.Null,
  'general' : IDL.Null,
  'sustainability' : IDL.Null,
  'agriculture' : IDL.Null,
});
export const TrainingResource = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'resourceType' : ResourceType,
  'category' : ResourceCategory,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const Entrepreneur = IDL.Record({
  'id' : IDL.Principal,
  'age' : IDL.Nat,
  'bio' : IDL.Text,
  'contactInfo' : IDL.Text,
  'businessCategory' : BusinessCategory,
  'fullName' : IDL.Text,
  'district' : IDL.Text,
  'state' : IDL.Text,
  'panchayat' : IDL.Text,
  'village' : IDL.Text,
  'gender' : Gender,
  'skills' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addCommunityPost' : IDL.Func([CommunityPost], [], []),
  'addSuccessStory' : IDL.Func([SuccessStory], [], []),
  'addTrainingResource' : IDL.Func([TrainingResource], [], []),
  'getEntrepreneur' : IDL.Func([IDL.Principal], [Entrepreneur], ['query']),
  'listCommunityPosts' : IDL.Func([], [IDL.Vec(CommunityPost)], ['query']),
  'listEntrepreneurs' : IDL.Func([], [IDL.Vec(Entrepreneur)], ['query']),
  'listSuccessStories' : IDL.Func([], [IDL.Vec(SuccessStory)], ['query']),
  'listTrainingResources' : IDL.Func(
      [],
      [IDL.Vec(TrainingResource)],
      ['query'],
    ),
  'registerEntrepreneur' : IDL.Func([Entrepreneur], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const BusinessCategory = IDL.Variant({
    'other' : IDL.Null,
    'food' : IDL.Null,
    'environment' : IDL.Null,
    'sustainability' : IDL.Null,
    'agriculture' : IDL.Null,
  });
  const CommunityPost = IDL.Record({
    'id' : IDL.Nat,
    'author' : IDL.Principal,
    'panchayat' : IDL.Text,
    'message' : IDL.Text,
    'village' : IDL.Text,
    'timestamp' : Time,
    'category' : BusinessCategory,
  });
  const SuccessStory = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Time,
    'authorName' : IDL.Text,
    'village' : IDL.Text,
    'category' : BusinessCategory,
  });
  const ResourceType = IDL.Variant({
    'video' : IDL.Null,
    'tool' : IDL.Null,
    'guide' : IDL.Null,
    'course' : IDL.Null,
  });
  const ResourceCategory = IDL.Variant({
    'food' : IDL.Null,
    'environment' : IDL.Null,
    'general' : IDL.Null,
    'sustainability' : IDL.Null,
    'agriculture' : IDL.Null,
  });
  const TrainingResource = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'resourceType' : ResourceType,
    'category' : ResourceCategory,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const Entrepreneur = IDL.Record({
    'id' : IDL.Principal,
    'age' : IDL.Nat,
    'bio' : IDL.Text,
    'contactInfo' : IDL.Text,
    'businessCategory' : BusinessCategory,
    'fullName' : IDL.Text,
    'district' : IDL.Text,
    'state' : IDL.Text,
    'panchayat' : IDL.Text,
    'village' : IDL.Text,
    'gender' : Gender,
    'skills' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addCommunityPost' : IDL.Func([CommunityPost], [], []),
    'addSuccessStory' : IDL.Func([SuccessStory], [], []),
    'addTrainingResource' : IDL.Func([TrainingResource], [], []),
    'getEntrepreneur' : IDL.Func([IDL.Principal], [Entrepreneur], ['query']),
    'listCommunityPosts' : IDL.Func([], [IDL.Vec(CommunityPost)], ['query']),
    'listEntrepreneurs' : IDL.Func([], [IDL.Vec(Entrepreneur)], ['query']),
    'listSuccessStories' : IDL.Func([], [IDL.Vec(SuccessStory)], ['query']),
    'listTrainingResources' : IDL.Func(
        [],
        [IDL.Vec(TrainingResource)],
        ['query'],
      ),
    'registerEntrepreneur' : IDL.Func([Entrepreneur], [], []),
  });
};

export const init = ({ IDL }) => { return []; };